### ISSUE TITLE
blob download super slow causing very long job run time

### ISSUE THREAD

**Issue by joeHickson** [epiforecasts/covid-rt-estimates-batch#6]
Jobs are taking around an hour to commit - mostly spent slowly ticking through:

``` bash
 az storage blob download-batch -d . --pattern "subnational/canada-full/cases/**/latest/*" -s results --account-name epinowcovidrstorage --auth-mode login && 
 az storage blob download-batch -d . --pattern "subnational/canada-full/cases/summary/*" -s results --account-name epinowcovidrstorage --auth-mode login && 
 az storage blob download-batch -d . --pattern "last-update/*" -s results --account-name epinowcovidrstorage --auth-mode login &&
 az storage blob download-batch -d . --pattern "*.csv" -s results --account-name epinowcovidrstorage --auth-mode login && 
```

Related issue suggests using az copy: https://github.com/Azure/azure-cli/issues/10741

Sadly the storage copy alternative doesn't seem able to restrict using wildcards on the directory - instead needing to pull the exact folder.
```
az storage copy -s https://epinowcovidrstorage.blob.core.windows.net/results/subnational/canada-full/
cases/summary --account-name epinowcovidrstorage -d subnational/canada-full/cases &&
```
a list of the dataset sublocations can be grabbed using
```
 az storage blob directory list -c results -d subnational/canada/cases/national --account-name epinowc
ovidrstorage --delimiter '/' --query '[].name | [?ends_with(@, `/`)]'
```
allowing for parsing over each one to grab the latest folder explicitly.

I think this problem will get progressively worse as the blob is holding all the old dated versions of every result set so steadily growing. Because copy isn't doing any clever searching it can pull very quickly - it seem storage blob download-batch with a pattern is searching everything in the blob and subsequently slowing with it's growth.

**Comment by sbfnk** [comment]
Fixed by switching to `azcopy` in #7
